### ISSUE TITLE
gogoanime domain name change

### ISSUE THREAD

**Issue by classicalokaku** [FireHead90544/SenPY#11]
hello, gogoanime changed the domain to https://anitaku.to/ please update senpy to use the domain as i cant download since they changed the domain

**Comment by classicalokaku** [comment]
can i get an update?

**Comment by classicalokaku** [comment]
can i get an update?

**Comment by classicalokaku** [comment]
can i get an update?

**Comment by FireHead90544** [comment]
I just got my semester break and would be working on this.

**Comment by FireHead90544** [comment]
Updated the domain, some fixes needed. The program's breaking. Will be fixing it by rewriting major portion. Stay tuned.
