### ISSUE TITLE
Why aren't the episodes in the right order

### ISSUE THREAD

**Issue by candrapersada** [FireHead90544/SenPY#12]
Why aren't the episodes downloaded in the correct order?
from 5 4 3 2 1
concurrent downloads 1
Release v1.1.0

**Comment by FireHead90544** [comment]
They should. I remember the episodes numbers being sorted before actually starting the download. Could you explain bit more what actually is happening? Like if they are getting downloaded, you could always sort it by name/date/size from your file manager later.

**Comment by candrapersada** [comment]
if you use custom episodes like 1-5
directly start downloading from 5 4 3 2 1 not from 1 2 3 4 5

**Comment by FireHead90544** [comment]
I don't think that's a problem though, the order of downloads shouldn't matter. All that matters is if all the mentioned episodes are getting downloaded or not.

Still, I'll check that behaviour out 👍

**Comment by FireHead90544** [comment]
@candrapersada 
This issue is fixed in [release v1.1.1](https://github.com/FireHead90544/SenPY/releases/tag/v1.1.1)
