### ISSUE TITLE
Gogoanime api

### ISSUE THREAD

**Issue by Arctic4161** [FireHead90544/SenPY#13]
The gogoanime Api that you use is no longer available so it doesn't download anymore and crashes.

**Comment by FireHead90544** [comment]
Thanks for mentioning, just checked and it is as you say. Updated the new api domain, pushing the changes.

**Comment by FireHead90544** [comment]
Fixed in [v1.1.2](https://github.com/FireHead90544/SenPY/releases/v1.1.2).

**Comment by FireHead90544** [comment]
Reopen if needed.
