### ISSUE TITLE
why is SenPY Character broken in conemu?

### ISSUE THREAD

**Issue by candrapersada** [FireHead90544/SenPY#17]
![image](https://github.com/FireHead90544/SenPY/assets/36833664/20c981b0-2195-4213-a210-91398272dcd2)
![image](https://github.com/FireHead90544/SenPY/assets/36833664/9602fc55-d877-48f2-a18e-d64e7587ddde)

**Comment by FireHead90544** [comment]
I guess this is because the terminal is not supporting true colors. Try using another terminal.

Could you write the steps to reproduce this?

**Comment by candrapersada** [comment]
> I guess this is because the terminal is not supporting true colors. Try using another terminal.

Yes working
