### ISSUE TITLE
No support for 'Previous' button in the CLI

### ISSUE THREAD

**Issue by RoyCoding8** [FireHead90544/SenPY#2]
When the SenPy application is opened, there is no "back" button to go to the previous screen. I think it would be nice to have one in case someone accidentally chooses the wrong option :)

**Comment by FireHead90544** [comment]
Oh yeah!! I totally forgot to add it. Thanks for the suggestion. I'll implement it in the meantime :)

**Comment by mihir1739** [comment]
Is it open to work on ?

**Comment by FireHead90544** [comment]
> Is it open to work on ?

Yeah, feel free to contribute, if you want to 😄

**Comment by FireHead90544** [comment]
Any updates?

**Comment by FireHead90544** [comment]
This issue is mentioned in Pull [#7](https://github.com/FireHead90544/SenPY/issues/7) and probably will be finished there so removing from picks here.

**Comment by FireHead90544** [comment]
Implemented already. Some fixes needed, will be doing it now.
