### ISSUE TITLE
limits the number of items which are downloaded concurrently

### ISSUE THREAD

**Issue by candrapersada** [FireHead90544/SenPY#4]
how to limits the number of items which are downloaded concurrently in aria2 or SenPY?
`--max-concurrent-downloads=<N>`

**Comment by FireHead90544** [comment]
I will be adding an option for this in the next update. Until then, you can change the `--max-concurrent-downloads=6` parameter in [this line](https://github.com/FireHead90544/SenPY/blob/main/main.py#L161) as a temporary measure.

**Comment by classicalokaku** [comment]
please add this feature

**Comment by FireHead90544** [comment]
Finally added this option in [v1.1.0](https://github.com/FireHead90544/SenPY/releases/tag/v1.1.0). You may find the option for this in the config file now.
