### ISSUE TITLE
Is there a chance this can be implemented to run on colab?

### ISSUE THREAD

**Issue by Purkid** [FireHead90544/SenPY#5]
I liked the idea of your previous project on downloading gogoanime to gdrive using colab but I can't figure out how to use it.

**Comment by FireHead90544** [comment]
Heyaa there again!
In context to your last issue and this one.
I would suggest looking at the newer implementation of this known as [SenPY](https://github.com/FireHead90544/SenPY), you can use the scraping logic of it and implement the same thing on Google Colab by taking reference from this repo itself.

Btw, your suggestion is pretty good. I'd be releasing a Google Colab version for SenPY in near future (which will allow you to download and save animes directly to your google drive).

Until then try fiddling with the code from both repositories.

**Comment by Purkid** [comment]
Thanks for your reply, and thank you for this project. 
I will try to make it for myself to make it run on colab, and I will message you if I accomplish it. 
Happy Holidays.

**Comment by FireHead90544** [comment]
Welcome.
Good luck with with, sure I would be more than glad to see you accomplish that :D
Let me know if you need some sort of help with it :)

**Comment by FireHead90544** [comment]
Reopen this Issue if you need any help.
