### ISSUE TITLE
My appliction not working

### ISSUE THREAD

**Issue by Legendary9029** [FireHead90544/SenPY#6]
I followed all the setup steps but my application doesn't start properly, it  opens a windows for about 0.2sec and then closes it self without showing any error messages, pl help me and I am thankful to you for making this wonderful apllication

**Comment by FireHead90544** [comment]
Hello @Legendary9029,
I am sorry for the inconvenience, just checked and found out the previous gogoanime domain (gogoanime.pe) has been blocked, so it was not accessible. I have updated it to gogoanime.ar for now.

The new build will be available pretty soon, download and use that one, it'll work hopefully.

**Comment by FireHead90544** [comment]
[The new release](https://github.com/FireHead90544/SenPY/releases/tag/v0.1.6) is pushed. You can download the working one, i.e, v0.1.6 here: [SenPY.exe](https://github.com/FireHead90544/SenPY/releases/download/v0.1.6/SenPY.exe).

**Comment by FireHead90544** [comment]
Reopen the issue, if you face any other problems.

**Comment by Legendary9029** [comment]
The same problem pursues, the applications starts but closes it self in just under a sec

**Comment by FireHead90544** [comment]
I cross-checked it myself and found it working, did you download the latest release? The [v0.1.6](https://github.com/FireHead90544/SenPY/releases/download/v0.1.6/SenPY.exe)?

**Comment by FireHead90544** [comment]
Try using a vpn if you are using v0.1.6, your ISP might have been blocking the gogoanime domain.
