### ISSUE TITLE
Github opens and closes itself

### ISSUE THREAD

**Issue by RaneKun** [FireHead90544/SenPY#9]
5 days ago also I downloaded 5 anime seasons using it but since today I am seeing that whenever I am opening SenPy.exe it doesn't display any options like download anime, update config file etc like it normally does, it stays on the black cmd screen for about 15 seconds then really quickly displays an error info and then closes itself and I can't even read that error line cause it happens just so quick and also the log file doesn't mention anything or sort, also I tried deleting existing files and redownloaded it and even deleted old config file but the problem still persists. Anybody knows what's causing this issue?

**Comment by RaneKun** [comment]
![image](https://github.com/FireHead90544/SenPY/assets/121618532/7b8d7dba-57f1-48ec-bb5d-653115d78c08)
Ok so I was able to record the screen and capture the error message and this is what I get, can anybody explain me this?

**Comment by RaneKun** [comment]
Actually nvm, I found a solution to the problem, just gotta use vpn 🥴

**Comment by FireHead90544** [comment]
Sorry for responding late, that might be because your ISP blocking gogoanime's domain. Using domain might work. Sometimes the domain itself would've been deleted so we needs update it on the code.
